name: ESLint Review with ReviewDog

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'

jobs:
  eslint-review:
    name: ESLint Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint with ReviewDog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Affiche les commentaires directement dans la PR
          eslint_flags: '.'
